#!/bin/bash

sed -i "s,LISTEN_PORT,$PORT,g" /etc/nginx/conf.d/app.conf

# install and lock composer packages
echo "Installing libraries..."

composer install

echo "Installed Libraries"

# run migrations and seed data
php artisan cache:clear

php artisan optimize:clear

echo "Migrating database..."

php artisan migrate

echo "Database migrated successfully"

# execute laravel pre-requisites
php artisan key:generate

php artisan optimize:clear

php artisan config:cache

# check the version of laravel framework
LARAVEL_VERSION=$(php artisan --version)

echo "The laravel version is ${LARAVEL_VERSION}"

# start admin queue job
php artisan queue:work --queue=admin &
echo "Running queue:work..."
# start background jobs
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
